version: '3.8'
services:
  web:
    container_name: containerWeb
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html

  db:
    container_name: containerDataBase
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atlas_db
      MYSQL_USER: atlas
      MYSQL_PASSWORD: root

  phpmyadmin:
    container_name: containerPhpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
